dikidi_client:
  service_provider_url: 'https://dikidi.net/550001?p=1.pi-ssm-sd&s=7937920&rl=0_0'
  event_provider_url: 'https://dikidi.net/ru/mobile/ajax/newrecord/get_datetimes/?company_id=550001'
  api_rate_limit: 3
  api_rate_burst: 1
auth_service:
  key_prefix: 'session'
polling_service:
  parser:
    number_pattern: '№\s*(\d+)'
    auditorium_pattern: '\((\d+)\s*\p{L}+\.\)'
    spot_pattern: '\((\d+)-?\p{L}*\s*место\)'
    topic_pattern: '(Оптика|Тв\.?\s*тело|Электричество|Механика|Виртуальная\s*лаб\.?)'
    name_prefix: 'Лабораторная работа'
    topic_map:
      'Оптика': 'Optics'
      'Тв. тело': 'Rigid Body'
      'Электричество': 'Electricity'
      'Механика': 'Mechanics'
      'Виртуальная лаб.': 'Virtual'
    type_map:
      'Аудиторное': 'Defence'
      'Выполнение': 'Performance'
    default_type: 'Performance'

subscription_service:
  deduplicator:
    key_prefix: 'slot'
    ttl: 30m
